In [2]:
import sys
sys.path.append("..")
from dataset.ravdess import Ravdess
r = Ravdess(root_dir="../dataset/ravdess")

In [7]:
lens = []
for x,y in r:
    lens.append(x.size()[1])

In [13]:
import numpy as np
# lens = np.array(lens)
lens.mean(), lens.std(), lens.max(), lens.min()

(177720.61024305556, 15997.88618116857, 253053, 142542)

In [31]:
wav = np.zeros(142542)
sr = 48000  #ker
sr14 = int(48000/4) # str


conv_out = int(( wav.shape[0] - sr  )/sr14 +1 ) 
print ( conv_out )


i = 0

while (i+sr < wav.shape[0]):
    
    print(i,i+sr)
    print ( wav[i:i+sr] )
    i+=sr14



8
0 48000
[0. 0. 0. ... 0. 0. 0.]
12000 60000
[0. 0. 0. ... 0. 0. 0.]
24000 72000
[0. 0. 0. ... 0. 0. 0.]
36000 84000
[0. 0. 0. ... 0. 0. 0.]
48000 96000
[0. 0. 0. ... 0. 0. 0.]
60000 108000
[0. 0. 0. ... 0. 0. 0.]
72000 120000
[0. 0. 0. ... 0. 0. 0.]
84000 132000
[0. 0. 0. ... 0. 0. 0.]


In [34]:
import torch

size = 142542
wav = torch.arange(size).view(1,-1)
#print(wav)
'''
    Genera una lista de ondas del mismo tamano size_segs
    tensor: 1xN 
    sr: Sampling Rate

'''
def window_wave( tensor , sr , size_segs=1 , stride_segs=0.25):
    nuevos_audios=[]

    size = size_segs * sr
    stride = int(stride_segs * sr)

    i=0
    while (i+size < tensor.shape[1]):
        nuevos_audios.append(wav[:,i:i+size])
        i+=stride 

    nuevos_audios.append(wav[:,tensor.shape[1]-size:tensor.shape[1]])
    return nuevos_audios
window_wave(wav,48000)
#for x in window_wave(wav,48000): print(x.shape)

tensor([[     0,      1,      2,  ..., 142539, 142540, 142541]])


[tensor([[    0,     1,     2,  ..., 47997, 47998, 47999]]),
 tensor([[12000, 12001, 12002,  ..., 59997, 59998, 59999]]),
 tensor([[24000, 24001, 24002,  ..., 71997, 71998, 71999]]),
 tensor([[36000, 36001, 36002,  ..., 83997, 83998, 83999]]),
 tensor([[48000, 48001, 48002,  ..., 95997, 95998, 95999]]),
 tensor([[ 60000,  60001,  60002,  ..., 107997, 107998, 107999]]),
 tensor([[ 72000,  72001,  72002,  ..., 119997, 119998, 119999]]),
 tensor([[ 84000,  84001,  84002,  ..., 131997, 131998, 131999]]),
 tensor([[ 94542,  94543,  94544,  ..., 142539, 142540, 142541]])]

In [33]:
(142542-132000)/142542

0.07395714947173465

In [2]:
import sys
sys.path.append("..")
from dataset.ravdess import Ravdess
from models.transforms import to_mfcc_compose
r = Ravdess(root_dir="../dataset/ravdess",transform=to_mfcc_compose,reset_aug=True)

Augment File


KeyboardInterrupt: 

In [4]:
 data_transform = to_mfcc_compose
 ravdess_train = Ravdess( "../dataset/ravdess", train=True , transform = data_transform )

In [8]:
len(ravdess_train)

x,y = ravdess_train[0]

x,y

(tensor([[[-8.6505, -8.6505, -8.6505,  ..., -7.3187, -7.0760, -7.5614],
          [ 0.1845,  0.1845,  0.1845,  ..., -0.3146, -0.4003, -0.0515],
          [ 0.1845,  0.1845,  0.1845,  ...,  0.0786,  0.0397,  0.2562],
          ...,
          [ 0.1845,  0.1845,  0.1845,  ...,  0.0794,  0.1464,  0.1080],
          [ 0.1845,  0.1845,  0.1845,  ...,  0.0697,  0.1324,  0.0842],
          [ 0.1845,  0.1845,  0.1845,  ...,  0.1886,  0.1479,  0.1188]]]),
 2)